# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    # target databases
    services:
      mysql:
        image: mysql:8.3.0-oraclelinux8
        env:
          MYSQL_DATABASE: graphdb2rdb
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
    # setup
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    # test
    - name: Run tests
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v4"
      with:
        fail_ci_if_error: true

    # formatter
    - name: Run sbt format
      run: sbt scalafmtAll
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply scalafmt Change
